"use client";

import { motion, useInView } from "framer-motion";
import { useRef } from "react";

import { publicEase } from "@/components/public/public-motion";

// ── Stage data ────────────────────────────────────────────────

const stages = [
  {
    id: "project",
    number: "01",
    label: "Project Context",
    icon: "📦",
    color: "bg-amber-100 text-amber-800",
    description:
      "A published project serves as the seed — complete with title, description, and technical content. The AI reads this as its knowledge base.",
    detail: {
      heading: "Analytics Platform for Game Studios",
      body: "A real-time analytics pipeline using embeddings and batch scoring. Built for mobile game studios.",
    },
  },
  {
    id: "idea",
    number: "02",
    label: "Idea Generation",
    icon: "💡",
    color: "bg-sky-100 text-sky-800",
    description:
      "The AI generates a blog idea from the project context: title, angle, target reader, and positioning notes — all schema-validated.",
    detail: {
      heading: "E2E Golden Path Blog Idea",
      body: "Semi-auto AI blog pipeline. Target: Engineering leaders. Prove generate-to-publish workflow with human gates.",
    },
  },
  {
    id: "outline",
    number: "03",
    label: "Outline",
    icon: "📋",
    color: "bg-purple-100 text-purple-800",
    description:
      "Structured outline with sections and talking points. Each section is reviewable before the draft stage begins.",
    detail: {
      sections: [
        { name: "Context", points: ["Why semi-auto matters"] },
        { name: "Workflow", points: ["Approve each gate", "Orchestrator runs next stage"] },
      ],
    },
  },
  {
    id: "draft",
    number: "04",
    label: "Draft Writer",
    icon: "✍️",
    color: "bg-emerald-100 text-emerald-800",
    description:
      "The agent writes a full draft with a human editor in mind. Markdown output, clean structure, ready for review.",
    detail: {
      body: "## Context\n\nSemi-auto keeps humans in the loop. Each gate requires approval before the next stage runs.\n\n## Workflow\n\nThe portal streamlines editorial QA for semi-auto blog pipelines, reducing review cycles from days to hours.",
    },
  },
  {
    id: "review",
    number: "05",
    label: "Technical Review",
    icon: "🔍",
    color: "bg-orange-100 text-orange-800",
    description:
      "Automated technical review checks factual accuracy, technical risk, and overall soundness before publication.",
    detail: {
      risk: "low",
      issues: [],
      recommendation: "approve",
    },
  },
  {
    id: "marketing",
    number: "06",
    label: "Marketing Metadata",
    icon: "📢",
    color: "bg-rose-100 text-rose-800",
    description:
      "SEO title, meta description, social copy for LinkedIn and X, and a call-to-action. All generated by AI, reviewed by humans.",
    detail: {
      seoTitle: "E2E Golden Path Blog Idea",
      metaDescription: "How the AI Lab Portal semi-auto blog pipeline works end to end.",
      cta: "Read the full workflow",
    },
  },
  {
    id: "publish",
    number: "07",
    label: "Publish",
    icon: "🚀",
    color: "bg-[var(--color-story-green)]/15 text-[var(--color-story-green)]",
    description:
      "One click publishes to the live blog. The entire pipeline — from project to published post — runs with deterministic fake LLM, no OpenAI key needed.",
    detail: {
      published: true,
      message: "Published to /blog/e2e-golden-path-blog-idea",
    },
  },
];

function StageCard({
  stage,
  index,
}: {
  stage: (typeof stages)[number];
  index: number;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <motion.div
      ref={ref}
      id={`tour-stage-${stage.id}`}
      className="relative mx-auto max-w-5xl px-6 py-24 first:pt-0 last:pb-32"
      initial={{ opacity: 0 }}
      animate={isInView ? { opacity: 1 } : {}}
      transition={{ duration: 0.6, ease: publicEase }}
    >
      <div className="grid items-start gap-12 lg:grid-cols-5">
        {/* Left: number + label + description */}
        <div className="lg:col-span-2 lg:sticky lg:top-32">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={isInView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 0.5, delay: 0.1, ease: publicEase }}
          >
            <span className="font-display text-[clamp(3rem,6vw,5rem)] leading-none tracking-[-0.04em] text-[var(--color-charcoal-black)]/10">
              {stage.number}
            </span>
            <div className="mt-4 flex items-center gap-3">
              <span className="flex size-10 items-center justify-center rounded-full border border-[var(--color-book-text-gray)]/15 bg-white text-lg shadow-sm">
                {stage.icon}
              </span>
              <h3 className="font-display text-2xl tracking-tight text-[var(--color-charcoal-black)]">
                {stage.label}
              </h3>
            </div>
            <p className="mt-4 text-sm leading-relaxed text-[var(--color-book-text-gray)]">
              {stage.description}
            </p>
          </motion.div>
        </div>

        {/* Right: detail card */}
        <div className="lg:col-span-3">
          <motion.div
            className="overflow-hidden rounded-2xl border border-[var(--color-book-text-gray)]/15 bg-white shadow-sm"
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.2, ease: publicEase }}
          >
            {/* Card header */}
            <div className="flex items-center gap-2 border-b border-[var(--color-book-text-gray)]/10 px-6 py-4">
              <div className="flex gap-1.5">
                <span className="size-2.5 rounded-full bg-red-400" />
                <span className="size-2.5 rounded-full bg-amber-400" />
                <span className="size-2.5 rounded-full bg-emerald-400" />
              </div>
              <span className="ml-2 text-[11px] font-medium text-[var(--color-muted-text-gray)] uppercase tracking-wider">
                AI Output — {stage.label}
              </span>
            </div>

            {/* Card body */}
            <div className="px-6 py-6">
              <StageContent stage={stage} />
            </div>
          </motion.div>
        </div>
      </div>

      {/* Connector line between stages */}
      {index < stages.length - 1 && (
        <div className="absolute bottom-0 left-1/2 h-12 w-px -translate-x-1/2 bg-gradient-to-b from-[var(--color-story-green)]/40 to-transparent" />
      )}
    </motion.div>
  );
}

function StageContent({ stage }: { stage: (typeof stages)[number] }) {
  if (stage.id === "project") {
    return (
      <div className="space-y-3">
        <h4 className="font-medium text-[var(--color-charcoal-black)]">{stage.detail.heading}</h4>
        <p className="text-sm leading-relaxed text-[var(--color-book-text-gray)]">{stage.detail.body}</p>
        <div className="mt-3 flex items-center gap-2 text-xs text-[var(--color-muted-text-gray)]">
          <span className="rounded-full border border-[var(--color-book-text-gray)]/15 px-2.5 py-1">published</span>
          <span className="rounded-full border border-[var(--color-book-text-gray)]/15 px-2.5 py-1">slug: e2e-project</span>
        </div>
      </div>
    );
  }

  if (stage.id === "idea") {
    return (
      <div className="space-y-3">
        <h4 className="font-medium text-[var(--color-charcoal-black)]">{stage.detail.heading}</h4>
        <p className="text-sm leading-relaxed text-[var(--color-book-text-gray)]">{stage.detail.body}</p>
        <div className="mt-2 space-y-1 text-sm text-[var(--color-book-text-gray)]">
          <div><span className="font-medium text-[var(--color-charcoal-black)]">Angle:</span> Semi-auto AI blog pipeline</div>
          <div><span className="font-medium text-[var(--color-charcoal-black)]">Reader:</span> Engineering leaders</div>
        </div>
      </div>
    );
  }

  if (stage.id === "outline") {
    return (
      <div className="space-y-4">
        {stage.detail.sections?.map((s) => (
          <div key={s.name}>
            <h4 className="text-sm font-medium text-[var(--color-charcoal-black)]">{s.name}</h4>
            <ul className="mt-1 space-y-1">
              {s.points.map((p) => (
                <li key={p} className="flex items-start gap-2 text-sm text-[var(--color-book-text-gray)]">
                  <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-[var(--color-story-green)]" />
                  {p}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    );
  }

  if (stage.id === "draft") {
    return (
      <div className="space-y-3">
        <h4 className="font-medium text-[var(--color-charcoal-black)]">Draft Preview</h4>
        <div className="rounded-lg bg-[var(--color-vellum-background)] p-4 text-sm leading-relaxed text-[var(--color-book-text-gray)]">
          <p className="font-medium text-[var(--color-charcoal-black)]">Context</p>
          <p>Semi-auto keeps humans in the loop. Each gate requires approval before the next stage runs.</p>
          <br />
          <p className="font-medium text-[var(--color-charcoal-black)]">Workflow</p>
          <p>The portal streamlines editorial QA for semi-auto blog pipelines, reducing review cycles from days to hours.</p>
        </div>
      </div>
    );
  }

  if (stage.id === "review") {
    return (
      <div className="space-y-3">
        <div className="flex items-center gap-2">
          <span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-medium text-emerald-700">
            Risk: {stage.detail.risk}
          </span>
          <span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-medium text-emerald-700">
            ✅ {stage.detail.recommendation}
          </span>
        </div>
        <p className="text-sm text-[var(--color-book-text-gray)]">
          No issues found. Technical review passed all automated checks.
        </p>
      </div>
    );
  }

  if (stage.id === "marketing") {
    return (
      <div className="space-y-3">
        <div className="space-y-1">
          <span className="text-[11px] font-medium uppercase tracking-wider text-[var(--color-muted-text-gray)]">SEO Title</span>
          <p className="text-sm font-medium text-[var(--color-charcoal-black)]">{stage.detail.seoTitle}</p>
        </div>
        <div className="space-y-1">
          <span className="text-[11px] font-medium uppercase tracking-wider text-[var(--color-muted-text-gray)]">Meta Description</span>
          <p className="text-sm text-[var(--color-book-text-gray)]">{stage.detail.metaDescription}</p>
        </div>
        <div className="space-y-1">
          <span className="text-[11px] font-medium uppercase tracking-wider text-[var(--color-muted-text-gray)]">CTA</span>
          <p className="text-sm text-[var(--color-story-green)]">{stage.detail.cta}</p>
        </div>
      </div>
    );
  }

  if (stage.id === "publish") {
    return (
      <div className="space-y-3">
        <div className="flex items-center gap-3">
          <span className="flex size-10 items-center justify-center rounded-full bg-[var(--color-story-green)]/15 text-lg">
            🚀
          </span>
          <div>
            <p className="font-medium text-[var(--color-charcoal-black)]">Published!</p>
            <p className="text-sm text-[var(--color-muted-text-gray)]">{stage.detail.message}</p>
          </div>
        </div>
        <p className="mt-4 text-sm leading-relaxed text-[var(--color-book-text-gray)]">
          The entire pipeline ran without a single OpenAI API call — fake LLM responses
          made the demo deterministic, reproducible, and verifiable in CI.
        </p>
      </div>
    );
  }

  return null;
}

export function TourPipeline() {
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-60px" });

  return (
    <section id="tour-pipeline" className="relative bg-[var(--color-vellum-background)]">
      {/* Section heading */}
      <div ref={ref} className="pt-28 text-center">
        <motion.div
          className="mx-auto max-w-2xl px-6"
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, ease: publicEase }}
        >
          <span className="mb-4 inline-block rounded-full border border-[var(--color-story-green)]/30 bg-[var(--color-story-green)]/8 px-4 py-1.5 text-[11px] font-medium tracking-wider uppercase text-[var(--color-story-green)]">
            The Pipeline
          </span>
          <h2 className="font-display text-[clamp(2rem,5vw,3.5rem)] leading-[1.05] tracking-[-0.03em] text-[var(--color-charcoal-black)]">
            From project to published
          </h2>
          <p className="mt-4 text-[var(--color-book-text-gray)]">
            Seven stages. Each one generates, reviews, and approves — with a human gate at every step.
          </p>
        </motion.div>
      </div>

      {/* Stages */}
      {stages.map((stage, i) => (
        <StageCard key={stage.id} stage={stage} index={i} />
      ))}
    </section>
  );
}
