from sqlalchemy import Boolean, Column, DateTime, Float, ForeignKey, Index, Integer, MetaData, String, Table, Text, UniqueConstraint, create_engine, text
from sqlalchemy.engine import Engine

from backend.app.settings import Settings

metadata = MetaData()


def create_database_engine(settings: Settings) -> Engine:
    return create_engine(str(settings.database_url), pool_pre_ping=True)

blog_posts = Table(
    "blog_posts",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("slug", String(160), nullable=False, unique=True),
    Column("title", String(240), nullable=False),
    Column("excerpt", Text, nullable=False),
    Column("author_name", String(120), nullable=False),
    Column("status", String(32), nullable=False),
    Column("published_at", DateTime(timezone=True), nullable=True),
    Column("content_markdown", Text, nullable=False),
    Column("image_url", String(2048), nullable=True),
    Column("author_user_id", String(255), nullable=True),
    Column("updated_at", DateTime(timezone=True), nullable=True),
)

user_follows = Table(
    "user_follows",
    metadata,
    Column("follower_user_id", String(255), nullable=False, primary_key=True),
    Column("followed_user_id", String(255), nullable=False, primary_key=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_user_follows_follower", "follower_user_id"),
    Index("ix_user_follows_followed", "followed_user_id"),
)

blog_tags = Table(
    "blog_tags",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("slug", String(80), nullable=False, unique=True),
    Column("name", String(120), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_blog_tags_slug", "slug"),
)

blog_post_tags = Table(
    "blog_post_tags",
    metadata,
    Column("post_id", String(64), ForeignKey("blog_posts.id", ondelete="CASCADE"), primary_key=True),
    Column("tag_id", String(64), ForeignKey("blog_tags.id", ondelete="CASCADE"), primary_key=True),
    Index("ix_blog_post_tags_post_id", "post_id"),
    Index("ix_blog_post_tags_tag_id", "tag_id"),
)

user_profiles = Table(
    "user_profiles",
    metadata,
    Column("user_id", String(255), ForeignKey("user.id", ondelete="CASCADE"), primary_key=True),
    Column("display_name", String(120), nullable=False),
    Column("bio", Text, nullable=True),
    Column("avatar_url", String(2048), nullable=True),
    Column("cover_url", String(2048), nullable=True),
    Column("website_url", String(2048), nullable=True),
    Column("github_url", String(2048), nullable=True),
    Column("linkedin_url", String(2048), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

showcases = Table(
    "showcases",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("slug", String(160), nullable=False, unique=True),
    Column("title", String(240), nullable=False),
    Column("hero_summary", Text, nullable=False),
    Column("industry", String(120), nullable=True),
    Column("use_case", String(240), nullable=True),
    Column("status", String(32), nullable=False),
    Column("published_at", DateTime(timezone=True), nullable=True),
    Column("content_markdown", Text, nullable=False),
    Column("image_url", String(2048), nullable=True),
    Index("ix_showcases_status_published_at", "status", "published_at"),
)

audit_events = Table(
    "audit_events",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("actor_user_id", String(128), nullable=False),
    Column("actor_email", String(320), nullable=False),
    Column("action", String(80), nullable=False),
    Column("entity_type", String(80), nullable=False),
    Column("entity_id", String(128), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_audit_events_entity", "entity_type", "entity_id"),
    Index("ix_audit_events_actor", "actor_user_id"),
)

blog_ideas = Table(
    "blog_ideas",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("title", String(240), nullable=False),
    Column("angle", String(160), nullable=False),
    Column("target_reader", String(160), nullable=False),
    Column("article_goal", Text, nullable=False),
    Column("positioning_notes", Text, nullable=True),
    Column("source", String(32), nullable=False),
    Column("source_project_context", Text, nullable=True),
    Column("status", String(32), nullable=False),
    Column("reviewed_by", String(128), nullable=True),
    Column("reviewed_at", DateTime(timezone=True), nullable=True),
    Column("feedback", Text, nullable=True),
    Column("outline_sections", Text, nullable=True),
    Column("outline_status", String(32), nullable=True),
    Column("draft_markdown", Text, nullable=True),
    Column("draft_status", String(32), nullable=True),
    Column("technical_review", Text, nullable=True),
    Column("technical_review_status", String(32), nullable=True),
    Column("marketing_metadata", Text, nullable=True),
    Column("marketing_status", String(32), nullable=True),
    Column("seo_audit", Text, nullable=True),
    Column("seo_audit_status", String(32), nullable=True),
    Column("published_blog_post_id", String(64), nullable=True),
    Column("scheduled_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_blog_ideas_status", "status"),
    Index("ix_blog_ideas_created_at", "created_at"),
    Index("ix_blog_ideas_outline_status", "outline_status"),
    Index("ix_blog_ideas_draft_status", "draft_status"),
    Index("ix_blog_ideas_review_status", "technical_review_status"),
    Index("ix_blog_ideas_marketing_status", "marketing_status"),
    Index("ix_blog_ideas_seo_audit_status", "seo_audit_status"),
    Index("ix_blog_ideas_published_blog_post_id", "published_blog_post_id"),
)

blog_post_revisions = Table(
    "blog_post_revisions",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("post_id", String(64), nullable=False),
    Column("revision_number", Integer, nullable=False),
    Column("title", String(240), nullable=False),
    Column("content_markdown", Text, nullable=False),
    Column("excerpt", Text, nullable=False),
    Column("slug", String(160), nullable=False),
    Column("image_url", String(2048), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("created_by_user_id", String(255), nullable=True),
    UniqueConstraint("post_id", "revision_number", name="uq_post_revision"),
    Index("ix_blog_post_revisions_post_id", "post_id"),
)


ai_runs = Table(
    "ai_runs",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("prompt_name", String(80), nullable=False),
    Column("prompt_version", String(32), nullable=False),
    Column("entity_type", String(64), nullable=False),
    Column("entity_id", String(64), nullable=False),
    Column("provider", String(32), nullable=False),
    Column("model", String(80), nullable=False),
    Column("status", String(32), nullable=False),
    Column("input_payload", Text, nullable=False),
    Column("output_payload", Text, nullable=True),
    Column("error_message", Text, nullable=True),
    Column("prompt_tokens", Integer, nullable=True),
    Column("completion_tokens", Integer, nullable=True),
    Column("total_tokens", Integer, nullable=True),
    Column("latency_ms", Integer, nullable=True),
    Column("trace_id", String(80), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_ai_runs_entity", "entity_type", "entity_id"),
    Index("ix_ai_runs_prompt", "prompt_name", "created_at"),
)

blog_generation_jobs = Table(
    "blog_generation_jobs",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("blog_idea_id", String(64), nullable=False),
    Column("stage", String(32), nullable=False),
    Column("celery_task_id", String(128), nullable=False),
    Column("status", String(32), nullable=False),
    Column("error_message", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Index("ix_blog_generation_jobs_idea", "blog_idea_id", "created_at"),
    Index("ix_blog_generation_jobs_celery_task_id", "celery_task_id", unique=True),
)

blog_claims = Table(
    "blog_claims",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("blog_idea_id", String(64), nullable=False),
    Column("claim_text", Text, nullable=False),
    Column("claim_type", String(32), nullable=False),
    Column("status", String(32), nullable=False),
    Column("evidence_source_type", String(32), nullable=True),
    Column("evidence_reference", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_blog_claims_idea", "blog_idea_id"),
)

news_sources = Table(
    "news_sources",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("name", String(160), nullable=False),
    Column("source_type", String(32), nullable=False),
    Column("url_or_identifier", String(512), nullable=False),
    Column("description", Text, nullable=True),
    Column("priority", String(16), nullable=False),
    Column("crawl_frequency_minutes", Integer, nullable=False),
    Column("is_enabled", Boolean, nullable=False),
    Column("credibility_base_score", Float, nullable=False),
    Column("last_crawled_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_news_sources_enabled", "is_enabled"),
    Index("ix_news_sources_type", "source_type"),
)

news_raw_items = Table(
    "news_raw_items",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("source_id", String(64), ForeignKey("news_sources.id", ondelete="CASCADE"), nullable=False),
    Column("external_id", String(512), nullable=False),
    Column("title", String(512), nullable=False),
    Column("link_url", String(1024), nullable=False),
    Column("published_at", DateTime(timezone=True), nullable=True),
    Column("raw_payload", Text, nullable=False),
    Column("content_hash", String(64), nullable=False),
    Column("fetched_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("source_id", "external_id", name="uq_news_raw_items_source_external"),
    Index("ix_news_raw_items_source", "source_id"),
    Index("ix_news_raw_items_fetched", "fetched_at"),
)

news_extracted_articles = Table(
    "news_extracted_articles",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("raw_item_id", String(64), ForeignKey("news_raw_items.id", ondelete="CASCADE"), nullable=False),
    Column("source_url", String(1024), nullable=False),
    Column("final_url", String(1024), nullable=True),
    Column("canonical_url", String(1024), nullable=True),
    Column("title", String(512), nullable=False),
    Column("author", String(256), nullable=True),
    Column("site_name", String(256), nullable=True),
    Column("published_at", DateTime(timezone=True), nullable=True),
    Column("content_markdown", Text, nullable=False),
    Column("content_text", Text, nullable=False),
    Column("content_hash", String(64), nullable=False),
    Column("provider", String(32), nullable=False),
    Column("extraction_status", String(32), nullable=False),
    Column("extraction_error", Text, nullable=True),
    Column("provider_latency_ms", Integer, nullable=True),
    Column("provider_payload", Text, nullable=True),
    Column("extracted_at", DateTime(timezone=True), nullable=False),
    Column("canonical_url_normalized", String(1024), nullable=False, server_default=""),
    Column("duplicate_status", String(32), nullable=False, server_default="unique"),
    Column(
        "duplicate_of_id",
        String(64),
        ForeignKey("news_extracted_articles.id", ondelete="SET NULL"),
        nullable=True,
    ),
    UniqueConstraint("raw_item_id", name="uq_news_extracted_articles_raw_item"),
    Index("ix_news_extracted_articles_status", "extraction_status"),
    Index("ix_news_extracted_canonical_normalized", "canonical_url_normalized"),
    Index("ix_news_extracted_content_hash", "content_hash"),
)

news_review_items = Table(
    "news_review_items",
    metadata,
    Column("id", String(64), primary_key=True),
    Column(
        "extracted_article_id",
        String(64),
        ForeignKey("news_extracted_articles.id", ondelete="CASCADE"),
        nullable=False,
    ),
    Column("raw_item_id", String(64), ForeignKey("news_raw_items.id", ondelete="CASCADE"), nullable=False),
    Column("source_id", String(64), ForeignKey("news_sources.id", ondelete="CASCADE"), nullable=False),
    Column("title", String(512), nullable=False),
    Column("source_credibility_score", Float, nullable=False),
    Column("engagement_score", Float, nullable=False),
    Column("relevance_score", Float, nullable=False),
    Column("novelty_score", Float, nullable=False),
    Column("technical_depth_score", Float, nullable=False),
    Column("business_value_score", Float, nullable=False),
    Column("spam_risk_score", Float, nullable=False),
    Column("final_publish_score", Float, nullable=False),
    Column("summary", Text, nullable=False),
    Column("why_it_matters", Text, nullable=False),
    Column("scorer_version", String(32), nullable=False),
    Column("review_status", String(32), nullable=False),
    Column("review_notes", Text, nullable=True),
    Column("scored_at", DateTime(timezone=True), nullable=False),
    Column("reviewed_at", DateTime(timezone=True), nullable=True),
    Column("slug", String(160), nullable=True, unique=True),
    Column("published_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("extracted_article_id", name="uq_news_review_items_extracted"),
    Index("ix_news_review_items_status", "review_status"),
    Index("ix_news_review_items_final_score", "final_publish_score"),
    Index("ix_news_review_items_slug", "slug"),
)

news_submitted_links = Table(
    "news_submitted_links",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("url", String(1024), nullable=False),
    Column("url_normalized", String(1024), nullable=False),
    Column("submitter_name", String(160), nullable=True),
    Column("submitter_email", String(320), nullable=True),
    Column("note", Text, nullable=True),
    Column("suggested_category", String(160), nullable=True),
    Column("rate_limit_key", String(128), nullable=False),
    Column("status", String(32), nullable=False),
    Column("processing_error", Text, nullable=True),
    Column("raw_item_id", String(64), ForeignKey("news_raw_items.id", ondelete="SET NULL"), nullable=True),
    Column(
        "review_item_id",
        String(64),
        ForeignKey("news_review_items.id", ondelete="SET NULL"),
        nullable=True,
    ),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("url_normalized", name="uq_news_submitted_links_url_normalized"),
    Index("ix_news_submitted_links_status", "status"),
    Index("ix_news_submitted_links_rate_key", "rate_limit_key"),
)

blog_reactions = Table(
    "blog_reactions",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("post_id", String(64), ForeignKey("blog_posts.id", ondelete="CASCADE"), nullable=False),
    Column("user_id", String(255), nullable=False),
    Column("user_email", String(320), nullable=True),
    Column("emoji", String(32), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("post_id", "user_id", "emoji", name="uq_blog_reactions_post_user_emoji"),
    Index("ix_blog_reactions_post_id", "post_id"),
)

blog_bookmarks = Table(
    "blog_bookmarks",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("post_id", String(64), ForeignKey("blog_posts.id", ondelete="CASCADE"), nullable=False),
    Column("user_id", String(255), nullable=False),
    Column("user_email", String(320), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("post_id", "user_id", name="uq_blog_bookmarks_post_user"),
    Index("ix_blog_bookmarks_user_id", "user_id"),
    Index("ix_blog_bookmarks_post_id", "post_id"),
)

blog_comments = Table(
    "blog_comments",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("post_id", String(64), ForeignKey("blog_posts.id", ondelete="CASCADE"), nullable=False),
    Column("user_id", String(255), nullable=False),
    Column("user_email", String(320), nullable=True),
    Column("user_name", String(160), nullable=True),
    Column("parent_id", String(64), ForeignKey("blog_comments.id", ondelete="SET NULL"), nullable=True),
    Column("content", Text, nullable=False),
    Column("status", String(32), nullable=False, server_default=text("'pending'")),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=True),
    Index("ix_blog_comments_post_id", "post_id"),
    Index("ix_blog_comments_status", "status"),
)

blog_comment_reactions = Table(
    "blog_comment_reactions",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("comment_id", String(64), ForeignKey("blog_comments.id", ondelete="CASCADE"), nullable=False),
    Column("user_id", String(255), nullable=False),
    Column("user_email", String(320), nullable=True),
    Column("emoji", String(32), nullable=False, server_default=text("'❤'")),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("comment_id", "user_id", name="uq_blog_cmt_react_comment_user"),
    Index("ix_blog_comment_reactions_comment_id", "comment_id"),
)

contact_messages = Table(
    "contact_messages",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("name", String(200), nullable=False),
    Column("email", String(320), nullable=False),
    Column("subject", String(500), nullable=False),
    Column("message", Text, nullable=False),
    Column("read_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

projects = Table(
    "projects",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("slug", String(160), nullable=False, unique=True),
    Column("title", String(240), nullable=False),
    Column("description", Text, nullable=False),
    Column("content_markdown", Text, nullable=False),
    Column("image_url", String(2048), nullable=True),
    Column("status", String(32), nullable=False),
    Column("published_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_projects_status_published_at", "status", "published_at"),
)

notifications = Table(
    "notifications",
    metadata,
    Column("id", String(64), primary_key=True),
    Column("user_id", String(255), nullable=False),
    Column("type", String(32), nullable=False),
    Column("actor_user_id", String(255), nullable=False),
    Column("actor_email", String(320), nullable=True),
    Column("actor_display_name", String(160), nullable=True),
    Column("resource_id", String(64), nullable=False, server_default=""),
    Column("resource_type", String(32), nullable=False, server_default=""),
    Column("read", Boolean, nullable=False, server_default=text("FALSE")),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_notifications_user_read", "user_id", "read"),
    Index("ix_notifications_user_created", "user_id", "created_at"),
)
