"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import {
  Sparkles,
  FileText,
  CheckCircle,
  XCircle,
  Clock,
  ArrowRight,
} from "lucide-react";

import { AdminEmptyState } from "@/components/admin/admin-empty-state";
import {
  AdminListActionForm,
  AdminListActionLink,
  AdminListActions,
  AdminListSubmitButton,
} from "@/components/admin/admin-list-actions";
import {
  adminIdeaPhaseClass,
  adminIdeaStatusClass,
  adminListPanelClass,
  adminListRowClass,
} from "@/components/admin/admin-ui";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

import { approveButtonLabel } from "./lib/pipeline-next-stage";

import type { BlogIdeaSummary } from "./page";

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

const statusConfig = {
  pending: { label: "Pending", icon: Clock },
  approved: { label: "Approved", icon: CheckCircle },
  rejected: { label: "Rejected", icon: XCircle },
} as const;

type PhaseTag = { kind: "neutral" | "ready" | "pending"; label: string };

function getPhaseTag(idea: BlogIdeaSummary): PhaseTag | null {
  if (idea.outline_status === "approved" && idea.draft_status === "approved") {
    return { kind: "ready", label: "Draft ready" };
  }
  if (idea.outline_status === "approved") {
    return { kind: "ready", label: "Outline ready" };
  }
  if (idea.outline_status === "pending") {
    return { kind: "pending", label: "Outline pending" };
  }
  if (idea.draft_status === "pending") {
    return { kind: "pending", label: "Draft pending" };
  }
  return null;
}

type Props = {
  ideas: BlogIdeaSummary[];
  approveIdeaAction: (formData: FormData) => Promise<void>;
  rejectIdeaAction: (formData: FormData) => Promise<void>;
  selectedIds?: Set<string>;
  onToggleSelect?: (id: string) => void;
};

const container = {
  hidden: {},
  show: {
    transition: { staggerChildren: 0.06 },
  },
};

const item = {
  hidden: { opacity: 0, y: 16 },
  show: { opacity: 1, y: 0, transition: { duration: 0.35, ease: "easeOut" as const } },
};

export function BlogIdeaCardList({
  ideas,
  approveIdeaAction,
  rejectIdeaAction,
  selectedIds,
  onToggleSelect,
}: Props) {
  if (ideas.length === 0) {
    return (
      <AdminEmptyState
        ctaHref="/admin/blog-ideas/new"
        ctaLabel="New idea"
        description="Ideas appear here when generated by AI or created manually. Create your first idea to get started."
        icon={<Sparkles className="size-6" aria-hidden />}
        title="No blog ideas yet"
      />
    );
  }

  return (
    <motion.ul
      variants={container}
      initial="hidden"
      animate="show"
      className={adminListPanelClass}
    >
      {ideas.map((idea) => {
        const StatusIcon = statusConfig[idea.status].icon;
        const phaseTag = getPhaseTag(idea);

        return (
          <motion.li
            key={idea.id}
            variants={item}
            layout
            className={cn(adminListRowClass, "group")}
          >
            <div className="flex items-start gap-3">
              {selectedIds && onToggleSelect ? (
                <input
                  type="checkbox"
                  className="mt-2 size-4 shrink-0 rounded border-border accent-brand"
                  checked={selectedIds.has(idea.id)}
                  onChange={() => onToggleSelect(idea.id)}
                />
              ) : null}
              <div className="min-w-0 flex-1">
              <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between sm:flex-wrap">
                {/* Left: Content */}
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    {/* Status badge */}
                    <Badge className={cn("gap-1 border-transparent", adminIdeaStatusClass(idea.status))} variant="secondary">
                      <StatusIcon className="size-3 shrink-0" aria-hidden />
                      {statusConfig[idea.status].label}
                    </Badge>

                    {phaseTag ? (
                      <Badge className={cn("border-transparent", adminIdeaPhaseClass(phaseTag.kind))} variant="secondary">
                        {phaseTag.label}
                      </Badge>
                    ) : null}

                    {/* Source */}
                    <span className="flex items-center gap-1 text-[11px] text-muted-foreground">
                      {idea.source === "ai_generated" ? (
                        <Sparkles className="size-3" />
                      ) : (
                        <FileText className="size-3" />
                      )}
                      {idea.source === "ai_generated" ? "AI" : "Manual"}
                    </span>
                  </div>

                  <Link
                    className="mt-2 block rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background"
                    href={`/admin/blog-ideas/${idea.id}`}
                  >
                    <h3 className="text-lg font-semibold leading-snug tracking-[-0.02em] text-foreground transition-colors group-hover:text-brand">
                      {idea.title}
                    </h3>
                  </Link>

                  <p className="mt-1 line-clamp-1 text-sm text-muted-foreground">
                    {idea.angle}
                  </p>

                  <p className="mt-2 text-xs text-muted-foreground">
                    {formatDate(idea.created_at)}
                  </p>
                </div>

                <AdminListActions>
                  {idea.status === "pending" ? (
                    <>
                      <AdminListActionForm action={approveIdeaAction}>
                        <input name="ideaId" type="hidden" value={idea.id} />
                        <AdminListSubmitButton variant="brand">
                          <CheckCircle className="size-3.5" aria-hidden />
                          {approveButtonLabel("idea")}
                        </AdminListSubmitButton>
                      </AdminListActionForm>
                      <AdminListActionForm action={rejectIdeaAction}>
                        <input name="ideaId" type="hidden" value={idea.id} />
                        <AdminListSubmitButton variant="outline">
                          <XCircle className="size-3.5" aria-hidden />
                          Reject
                        </AdminListSubmitButton>
                      </AdminListActionForm>
                    </>
                  ) : null}

                  <AdminListActionLink href={`/admin/blog-ideas/${idea.id}`} variant="ghost">
                    Details
                    <ArrowRight className="size-3 transition-transform group-hover:translate-x-0.5" aria-hidden />
                  </AdminListActionLink>
                </AdminListActions>
              </div>
            </div>
            </div>
          </motion.li>
        );
      })}
    </motion.ul>
  );
}
