"""Pydantic models for LLM structured outputs used by the AI Blog Agent.

Each model defines the expected JSON shape that the LLM must return.
The Blog Agent workflow uses these schemas as the `response_format` parameter
when calling the OpenAI structured output API, so the response is validated
at the API boundary instead of with post-hoc parsing.
"""

from pydantic import BaseModel, Field


class BlogIdea(BaseModel):
    """A blog idea generated from an internal project or external trend."""

    title: str = Field(description="Suggested blog post title", max_length=240)
    angle: str = Field(
        description="The specific angle or framing of the article",
        max_length=160,
    )
    target_reader: str = Field(
        description="Target audience (e.g. CTO, product manager, founder)",
        max_length=160,
    )
    article_goal: str = Field(
        description="What this article should accomplish for the reader"
    )
    positioning_notes: list[str] = Field(
        default_factory=list,
        description="Guidance for tone, claims, and positioning",
    )


class BlogOutlineSection(BaseModel):
    """A single section in a blog post outline."""

    section: str = Field(description="Section heading (e.g. Context, Problem, etc.)")
    points: list[str] = Field(
        description="Key points to cover in this section",
    )


class BlogOutline(BaseModel):
    """A structured article outline generated from a blog idea."""

    title: str = Field(description="Refined article title")
    outline: list[BlogOutlineSection] = Field(
        description="Ordered list of sections and their key points",
    )


class BlogDraft(BaseModel):
    """A full first draft in markdown format."""

    title: str = Field(description="Article title")
    markdown: str = Field(
        description=(
            "Full article markdown content, including all outline sections. "
            "Minimum 1,800 words; use ## headings per section."
        ),
    )


class BlogDraftSection(BaseModel):
    """One outline section expanded into publication-ready prose."""

    markdown: str = Field(
        description=(
            "Section body only (no heading). Write 250–400 words of natural "
            "English with concrete examples from the project context."
        ),
    )


class TechnicalReviewIssue(BaseModel):
    """A single issue found during technical review."""

    severity: str = Field(
        description="Severity level: high, medium, or low",
        pattern=r"^(high|medium|low)$",
    )
    issue_type: str = Field(
        description="Type of issue found",
        alias="type",
    )
    text: str = Field(description="The problematic text from the draft")
    reason: str = Field(description="Why this is an issue")
    suggestion: str = Field(
        description="Suggested fix or rephrase for the author",
    )


class TechnicalReview(BaseModel):
    """AI technical review of a blog draft."""

    overall_risk: str = Field(
        description="Overall risk level: low, medium, or high",
        pattern=r"^(low|medium|high)$",
    )
    issues: list[TechnicalReviewIssue] = Field(
        default_factory=list,
        description="Issues found during review, sorted by severity",
    )
    approval_recommendation: str = Field(
        description="Recommendation: approve, needs_revision, or reject",
        pattern=r"^(approve|needs_revision|reject)$",
    )


class ExtractedClaim(BaseModel):
    """A single claim identified in a blog draft."""

    claim_text: str = Field(description="Sentence or phrase containing the claim")
    claim_type: str = Field(
        description="performance, quantified, product_capability, opinion, or other",
        pattern=r"^(performance|quantified|product_capability|opinion|other)$",
    )
    requires_evidence: bool = Field(
        description="True when publishing should require evidence or waiver",
    )


class ClaimExtractionResult(BaseModel):
    """Structured claim ledger extracted from a draft."""

    claims: list[ExtractedClaim] = Field(default_factory=list)


class NewsScoring(BaseModel):
    """Structured LLM scoring output for an extracted AI News article."""

    source_credibility_score: float = Field(ge=0.0, le=1.0)
    engagement_score: float = Field(ge=0.0, le=1.0)
    relevance_score: float = Field(ge=0.0, le=1.0)
    novelty_score: float = Field(ge=0.0, le=1.0)
    technical_depth_score: float = Field(ge=0.0, le=1.0)
    business_value_score: float = Field(ge=0.0, le=1.0)
    spam_risk_score: float = Field(ge=0.0, le=1.0)
    final_publish_score: float = Field(ge=0.0, le=1.0)
    summary: str = Field(description="Concise factual summary for the review queue")
    why_it_matters: str = Field(description="Editorial note explaining why this item matters")


class MarketingMetadata(BaseModel):
    """SEO and social media metadata generated by the Marketing Editor."""

    seo_title: str = Field(description="SEO-optimized title (max 60 characters)")
    meta_description: str = Field(
        description="Meta description (max 160 characters)",
    )
    excerpt: str = Field(description="Short blog excerpt for listings")
    linkedin_post: str = Field(
        description="LinkedIn post promoting the article",
    )
    x_post: str = Field(
        description="X/Twitter post promoting the article (max 280 characters)",
    )
    cta: str = Field(
        description="Call to action for the end of the article",
    )
